#!/usr/bin/env python3
r"""
inject_deathclaw_egg_directions.py — port the DF farming-guide directions onto
the BNB Deathclaw Egg fixed-spawn markers, one block per individual spawn.

Sources (both DuchessFlame pages, merged):
  https://www.theduchessflame.com/post/where-to-farm-for-deathclaw-eggs
  https://www.theduchessflame.com/post/where-to-find-and-how-to-farm-for-deathclaws-and-deathclaw-meat-in-fallout-76

Directions are hand-authored content (like photos), so they live in the dist JSON
and are preserved across rebuilds by spawns_engine.build.load_existing:
  - MARKER_DIRECTIONS  -> marker-level `directions`, renders as "Getting there" on
                          multi-spawn markers. Preserved by (region, marker).
  - SPAWN_DIRECTIONS   -> per-spawn `directions`, keyed by REF so the text survives
                          a marker rename (e.g. Excelsior -> Ella Ames' Bunker) and
                          a re-sort of the spawns array.

Images: `image_top` / `image_bottom` are left EMPTY so the renderer keeps showing
its "… image coming soon" placeholder — a real-looking path that 404s would render
as a broken image on the live page. The intended filename for each slot is written
to the companion fields `image_top_planned` / `image_bottom_planned`, generated by
plan_path() to the site's existing convention:

    /wp-content/uploads/guide-images/farming/Deathclaw-Egg-Locations/
        {region}-{marker}-{spawn}-map.avif    (map location)
        {region}-{marker}-{spawn}-item.avif   (item in place)

To publish a photo: upload it at the planned path, then move that string from
`image_*_planned` into `image_*`.

Idempotent: re-running overwrites the same fields with the same text. Applies to
dist/farming_spawns/ and dist/pts/farming_spawns/ if present.
"""
import json, os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

IMG_BASE = "/wp-content/uploads/guide-images/farming-eggs/deathclaw-eggs"
# Local staging folder holding the converted AVIFs. Any planned filename that
# exists here is promoted from image_*_planned into the live image_* field.
AVIF_DIR = os.path.join(
    os.environ.get("DFBNB_GUIDES", os.path.expanduser("~/OneDrive/Guides and Stuff")),
    ".Farming - Eggs", "Deathclaw Egg", "AVIF for Upload",
)


# ─────────────────────────────────────────────────────────────────────────────
# Marker-level "Getting there" text — multi-spawn markers only. Covers the walk
# TO the POI; the per-spawn text below covers "behind the third rock".
# ─────────────────────────────────────────────────────────────────────────────
MARKER_DIRECTIONS = {
    "Tunnel of Love": (
        "These locations are accessible whether the Nuka-World on Tour event is "
        "running or not. After entering the Tunnel of Love, face north and follow "
        "the train tracks until you reach the area with the pink heart lights. "
        "Turn left, pass the orange forklift, and stop at the second set of "
        "tracks. Turn left again and walk forward into a small cave — four nests "
        "are piled up on your right. The fifth sits on its own up the scaffolding "
        "at the far end of the tracks. Note that the DF guide counts three nests "
        "in the pile; the game files place four, and they overlap heavily, so "
        "move your cursor around to pick out each separate loot window."
    ),
    "Deathclaw Island": (
        "Both eggs sit at the Deathclaw nest. The eggs can be hidden under the "
        "dirt when the Deathclaw pops out, so lead the Deathclaw away from the "
        "nest before killing it — that way you can loot the nest without the body "
        "getting in the way or covering the loot. Also check the white suitcase "
        "on the side of the nest; it can sometimes spawn additional Deathclaw eggs."
    ),
    "Hopewell Cave": (
        "From the fast travel point, run straight across the road and enter the "
        "cave. Everything below is described from the first nest, which is on the "
        "left-hand side of the cave just past the small pond of water near the "
        "entrance."
    ),
    "Abandoned Waste Dump": (
        "External approach — no load screen. From the fast travel point, walk "
        "forward and jump over the gate, then head toward the back of the truck, "
        "keeping the trailer on your left. The two nests and the loose egg all sit "
        "along the length of that truck. (The internal cavern below the dump is a "
        "separate marker — see Cavern, also in The Mire.)"
    ),
    "Cavern": (
        "This is the internal cavern beneath the Abandoned Waste Dump — it "
        "requires a load screen to enter. Once inside, walk past the rad barrels "
        "and stop at the bottom of the ramp. Turn left and keep the wall on your "
        "left-hand side the whole time you are in the cavern; it will lead you to "
        "the three Deathclaw nests in turn. The last nest you reach has a "
        "fixed-spawn Deathclaw Egg next to it."
    ),
    "Dino Peaks Mini Golf": (
        "From the spawn-in location, face north and run forward, stopping just "
        "past the Welcome to Dino Peak entrance sign. Turn left and walk over to "
        "the Hole 1 sign, then line yourself up with the Hole 1 putting green and "
        "follow it to the end. The six nests run in sequence from there along "
        "Holes 3 to 6, and each block below picks up where the previous one ends. "
        "Several sit on top of the putting greens and stairs and can be partly "
        "covered by dirt depending on how the Deathclaw exits, so wave your cursor "
        "around to find the loot window."
    ),
}


# ─────────────────────────────────────────────────────────────────────────────
# Per-spawn directions, keyed by REF (the FormID of the placed reference).
# Ref keying beats label keying: labels are regenerated from the breakdown on
# every build, so a re-sort would silently move text onto the wrong spawn.
# ─────────────────────────────────────────────────────────────────────────────
SPAWN_DIRECTIONS = {

    # ── Ash Heap · Tunnel of Love (5 nests) ─────────────────────────────────
    # Four are packed into one pile in the small cave; the fifth is isolated
    # up the scaffolding. Positions within the pile are taken from the placed
    # coordinates, since the nests overlap and can't be told apart by eye.
    "6747E9": (  # Nest #1 — the isolated one, far from the pile
        "The nest on its own, away from the pile. From the pile of nests, turn "
        "around and follow the tracks to the end. Turn right and walk along the "
        "road wall until you reach some scaffolding with a wooden ramp leading up. "
        "Follow the ramp to the top of the scaffolding, turn left, and follow the "
        "path until you see a break in the fence and a small cave on your left. "
        "This nest is inside that cave."
    ),
    "674813": (  # pile — northmost
        "One of the four nests piled up on your right in the small cave, past the "
        "orange forklift and the second set of tracks. This is the nest at the "
        "back of the pile (the northern-most of the four)."
    ),
    "67AE18": (  # pile — eastmost
        "One of the four nests piled up on your right in the small cave. This is "
        "the right-hand nest of the pile (the eastern-most of the four)."
    ),
    "67E92A": (  # pile — westmost
        "One of the four nests piled up on your right in the small cave. This is "
        "the left-hand nest of the pile (the western-most of the four)."
    ),
    "67E952": (  # pile — southmost
        "One of the four nests piled up on your right in the small cave. This is "
        "the nest at the front of the pile (the southern-most of the four), "
        "closest to you as you walk in."
    ),

    # ── Burning Springs ─────────────────────────────────────────────────────
    "80F840": (  # Ash Cave — single spawn
        "From the spawn-in location, line yourself up with the Ash Cave map marker "
        "and run straight up the hill. Continue forward and stop at the top of the "
        "stairs. Veer right and follow the path straight (north-ish) until you "
        "reach the pond. Turn right and enter the small cave — the Deathclaw Egg "
        "is against the north wall, behind the Brain Fungus and near the "
        "bobblehead spawn."
    ),
    "84B014": (  # The Rust Kingdom — single spawn
        "From the spawn-in location, face southwest and run straight until you "
        "reach the cliff wall in the distance. At the cliff face, turn left and "
        "use the machinery in front of you to climb to the rock ledge above. On "
        "the ledge, face north — the Deathclaw Egg is directly in front of you."
    ),
    "831130": (  # Highway Town Interior — single spawn, not on the DF page
        "Highway Town Interior is a Burning Springs interior — it requires a load "
        "screen to enter. One loose Deathclaw Egg spawns inside. This spot is not "
        "on the DuchessFlame guide, so step-by-step directions and photos are "
        "still to come."
    ),

    # ── Burning Springs · Dino Peaks Mini Golf (2 eggs + 6 nests) ────────────
    # The DF guide walks the six nests in sequence. Matching its compass legs
    # (N, E, E, S, SW) against the placed coordinates gives this order:
    #   82A3B2 -> 7F0A84 -> 80391B -> 82A3B3 -> 7F0A81 -> 82A3B4
    # and the two eggs sit on top of the 1st and 4th nests, exactly as the guide
    # says ("an egg can also spawn on top of this nest").
    "82A3B2": (  # Nest #4 in the array = nest 1 on the route (Hole 3)
        "Nest 1 of 6. From the end of the Hole 1 putting green, face north, go up "
        "the stairs and stop at Hole 2. Turn northwest and you'll see Hole 3. Walk "
        "over to Hole 3 and follow the putting green to the end — this is the "
        "first nest. Deathclaw Egg #1 can also spawn on top of it."
    ),
    "82A3B5": (  # Egg #1 — on nest 82A3B2
        "Sits on top of the Hole 3 nest (Deathclaw Nest #1), the first nest on the "
        "route. Follow the Hole 3 putting green to the end and check the top of "
        "the nest."
    ),
    "7F0A84": (  # Nest #2 in the array = nest 2 on the route
        "Nest 2 of 6. Stand on top of the Hole 3 nest and face north, then take a "
        "few steps forward — you'll be standing on this nest. It can be partially "
        "covered by dirt depending on how the Deathclaw exits, so move your cursor "
        "around slightly to find the inventory window."
    ),
    "80391B": (  # Nest #3 in the array = nest 3 on the route
        "Nest 3 of 6. Stand on the previous nest and face east. Go up the stairs "
        "and follow the blood trail to a small sign with an arrow, then continue "
        "up the stairs directly in front of you. This nest is at the top of those "
        "stairs. It is also covered in dirt, so you'll need to move your cursor "
        "around a bit to interact with it."
    ),
    "82A3B3": (  # Nest #5 in the array = nest 4 on the route (Hole 5)
        "Nest 4 of 6. Stand on top of the previous nest and face east. Walk "
        "forward and stop at the nest at the end of Hole 5. Deathclaw Egg #2 can "
        "also spawn on top of this nest."
    ),
    "82A3B6": (  # Egg #2 — on nest 82A3B3
        "Sits on top of the Hole 5 nest (Deathclaw Nest #4), the fourth nest on "
        "the route. Follow the Hole 5 putting green to the end and check the top "
        "of the nest."
    ),
    "7F0A81": (  # Nest #1 in the array = nest 5 on the route
        "Nest 5 of 6. Stand on top of the Hole 5 nest and face south. Walk forward "
        "and stop at the bottom of the stairs, then turn left and take a few steps "
        "forward to reach this nest. This one is also covered in dirt, so wave "
        "your cursor around to find the loot window."
    ),
    "82A3B4": (  # Nest #6 in the array = nest 6 on the route (Hole 6)
        "Nest 6 of 6. Stand on top of the previous nest and face southwest. Walk "
        "over to the start of Hole 6 directly in front of you, then follow the "
        "putting green to the end to find the final Deathclaw nest in this area."
    ),

    # ── Forest ──────────────────────────────────────────────────────────────
    "312301": (  # Arktos Pharma — single spawn
        "From the fast travel point, run straight through the doorway to the "
        "bottom of the stairs. Turn left, pass the Nuka-Cola and Medical Supplies "
        "machines, and run up the stairs in front of you. Follow the corridor "
        "around, pass the Arktos Pharma sign, and enter the doorway on your left. "
        "Continue straight and enter the second doorway on your left. Head "
        "slightly right and walk through the gap in the wall directly opposite. "
        "Jump down to ground level, turn around, and enter the doorway marked "
        "Protein Sequencing. Turn right and walk down the stairs — the Deathclaw "
        "Egg is on the metal shelves in front of you."
    ),
    "0638D1": (  # Deathclaw Island — western egg
        "The western of the two eggs, on the Deathclaw nest itself. Lead the "
        "Deathclaw away from the nest before killing it, so the body doesn't cover "
        "the loot, and check under the dirt if the egg isn't immediately visible."
    ),
    "0638D2": (  # Deathclaw Island — eastern egg, ~a few steps along
        "The eastern of the two eggs, a few steps along on the far side of the "
        "nest. Also worth checking the white suitcase on the side of the nest — it "
        "can sometimes spawn additional Deathclaw eggs."
    ),

    # ── Savage Divide ───────────────────────────────────────────────────────
    "36C927": (  # Hopewell Cave — the nest
        "The first Deathclaw nest, on the left-hand side of the cave just past the "
        "small pond of water near the entrance. Deathclaw Egg #1 can spawn on top "
        "of this nest."
    ),
    "62A86C": (  # Hopewell Cave — egg on the nest
        "Sits on top of the first Deathclaw nest, on the left-hand side of the "
        "cave just past the small pond of water near the entrance."
    ),
    "62A86F": (  # Hopewell Cave — eastern egg, back of the cave
        "From the nest, turn and face east. Walk forward to the back of the cave "
        "until you reach a rock face, then turn left. This Deathclaw Egg spawns "
        "behind the Firecracker Berry bush."
    ),
    "62A873": (  # Hopewell Cave — egg past the campfire
        "From the nest, turn and face west. Follow the edge of the pond as it "
        "curves around the cave, continuing along the water until you see a small "
        "campfire and a sleeping bag. This egg is behind the sleeping bag, against "
        "the rock face and to the left of a Firecracker Berry bush — the final "
        "Deathclaw Egg spawn for this area."
    ),
    "4F4CC1": (  # Monorail Elevator — single spawn
        "Note: you need the Marsupial mutation to reach this spot. From the fast "
        "travel point, follow the road until you reach the main pillar with the "
        "elevator at the bottom. Enter the elevator and select floor 2 — make sure "
        "you press 2, as the wrong floor takes you to a different area. Exit and "
        "follow the path to your left, continuing until you reach a building. Jump "
        "onto the roof and follow it around, keeping to the left and away from the "
        "edge — the Deathclaw Egg is in the far corner as part of a picnic scene."
    ),
    "5DD49E": (  # Enclave Research Facility — unreachable cell
        "Heads-up: the Enclave Research Facility interior cannot be entered in "
        "normal gameplay — there is no accessible door or load-door into this "
        "cell. A loose Deathclaw Egg is placed here in the game files (ref "
        "5DD49E), but because the location can't be reached, the egg cannot "
        "actually be collected. It is listed here for completeness only."
    ),

    # ── Skyline Valley ──────────────────────────────────────────────────────
    "786717": (  # Vault 63 · Atrium Upper Level — single spawn
        "Vault 63 — Atrium Upper Level. One Deathclaw Egg spawns on the atrium's "
        "upper level. Step-by-step directions and photos are still to come."
    ),

    # ── The Mire · Abandoned Waste Dump (external) ──────────────────────────
    "3DC3DD": (  # Nest #1 — behind the dead brahmin
        "From the fast travel point, walk forward and jump over the gate, then "
        "head toward the back of the truck keeping the trailer on your left. On "
        "your right you'll see a dead brahmin and a radiation barrel — this "
        "Deathclaw nest is behind the brahmin."
    ),
    "3DC449": (  # Nest #2 — behind the dead Yao Guai at the cab
        "Continue following the trailer until you reach the cab of the truck. In "
        "front of you will be a dead Yao Guai — this Deathclaw nest is behind it, "
        "with the loose Deathclaw Egg sitting alongside."
    ),
    "3DC447": (  # loose egg — beside nest 3DC449
        "At the cab of the truck, behind the dead Yao Guai and right beside "
        "Deathclaw Nest #2. This one is a fixed loose egg, not a nest roll."
    ),

    # ── The Mire · Cavern (internal, beneath the Waste Dump) ────────────────
    # The DF guide only says "keep the wall on your left and it leads you to the
    # three nests in turn", and names the LAST one as the nest with the fixed egg
    # next to it — which the coordinates confirm is 1A6435. The other two are
    # described by their position in the cavern rather than a guessed walk order.
    "1837FD": (  # northern nest
        "One of the first two nests you pass while following the left-hand wall. "
        "This is the nest in the northern part of the cavern, the furthest from "
        "the ramp you came down."
    ),
    "1A6460": (  # western nest
        "One of the first two nests you pass while following the left-hand wall. "
        "This is the nest over on the western side of the cavern."
    ),
    "1A6435": (  # eastern nest — the last one, with the fixed egg
        "The last of the three nests, over on the eastern side of the cavern. The "
        "fixed-spawn Deathclaw Egg sits right next to this one."
    ),
    "022E32": (  # loose egg beside 1A6435
        "Next to Deathclaw Nest #3 on the eastern side of the cavern — the last "
        "nest you reach following the left-hand wall. This is a fixed loose egg, "
        "so it does not depend on a nest roll."
    ),

    # ── The Mire · single-spawn nest markers ───────────────────────────────
    "37BE5C": (  # Thunder Mt. Power Plant Yard
        "From the fast travel point, follow the road south until you reach the end "
        "of the limo. Turn left, pass the tank, and enter the workshop yard. "
        "Continue straight along the road until you reach the green shipping "
        "containers near the water's edge. Jump over the railing and keep the "
        "concrete wall on your right as you follow it along. At the end of the "
        "wall, line yourself up between south and the Braxson's Quality Medical "
        "Supplies map icon, then walk forward along the riverbank. As the bank "
        "begins to curve, look to your right for the Deathclaw nest."
    ),
    "2C089D": (  # Ella Ames' Bunker
        "Stand at the door of Ella Ames' Bunker and look toward the blue ute in "
        "the water ahead of you. Behind the ute are four trees arranged in a loose "
        "semicircle. Starting from the left, head toward the third tree; stand "
        "behind it and look for a tree stump and a light-coloured tree with red "
        "leaves in front of you. Run to the red-leafed tree, then turn south and "
        "walk to the river's edge. Turn left and follow the riverbank — just past "
        "the curve in the bank, the Deathclaw nest is on your right."
    ),
}


# ─────────────────────────────────────────────────────────────────────────────
# Walk order
#
# The build sorts a marker's spawns by (source_type, ref), which is stable but
# arbitrary on the ground — at Dino Peaks it put the Hole 3 nest fourth. The
# photographs are numbered in WALK order, and so are the directions above
# ("Nest 1 of 6"), so the JSON is re-sorted to match and the labels renumbered
# from the new positions. Ref -> text/photo bindings are unaffected: everything
# is keyed by ref, and the label is regenerated, never used as a key.
#
# Grouping still follows the breakdown note (loose eggs before nests, per the
# spawn-guide spec); the ordering below applies WITHIN each group.
# ─────────────────────────────────────────────────────────────────────────────
SPAWN_ORDER = {
    # Route order confirmed two ways: DF's compass legs (N, E, E, S, SW) chained
    # against the placed coordinates, and "Dino Peaks Nest 1.jpg" showing the
    # HOLE 3 - STEGOSAURUS STEPS sign.
    "Dino Peaks Mini Golf": [
        "82A3B5", "82A3B6",                                    # eggs (on nests 1 and 4)
        "82A3B2", "7F0A84", "80391B", "82A3B3", "7F0A81", "82A3B4",
    ],
    # The pile in the small cave comes first, the scaffolding nest last.
    "Tunnel of Love": ["674813", "67AE18", "67E92A", "67E952", "6747E9"],
    # DF names the LAST nest as the one with the fixed egg beside it — 1A6435.
    "Cavern": ["022E32", "1837FD", "1A6460", "1A6435"],
    # Nest 1 is behind the dead brahmin, nest 2 behind the Yao Guai at the cab.
    "Abandoned Waste Dump": ["3DC447", "3DC3DD", "3DC449"],
    # Egg 1 on the nest, egg 2 at the berry bush, egg 3 behind the sleeping bag.
    "Hopewell Cave": ["62A86C", "62A86F", "62A873", "36C927"],
    "Deathclaw Island": ["0638D1", "0638D2"],
}

# label stem per source_type, used when renumbering
TYPE_LABEL = {"direct": "Deathclaw Egg", "nest": "Deathclaw Nest"}


def reorder_and_relabel(loc):
    """Sort a marker's spawns into walk order and renumber the labels."""
    spawns = loc.get("spawns") or []
    order = SPAWN_ORDER.get(loc.get("marker", ""))
    if order and len(spawns) > 1:
        rank = {r.upper(): i for i, r in enumerate(order)}
        spawns.sort(key=lambda s: rank.get((s.get("ref") or "").upper(), 999))
    # renumber within each source_type, in the (new) array order
    counts = {}
    for s in spawns:
        counts[s.get("source_type")] = counts.get(s.get("source_type"), 0) + 1
    seen = {}
    for s in spawns:
        st = s.get("source_type")
        stem = TYPE_LABEL.get(st) or (s.get("label") or "Spawn").split(" #")[0]
        seen[st] = seen.get(st, 0) + 1
        s["label"] = stem if counts.get(st, 0) == 1 else "%s #%d" % (stem, seen[st])
    loc["spawns"] = spawns
    # keep refs[] in step with the spawn order
    if spawns:
        loc["refs"] = [s.get("ref") for s in spawns if s.get("ref")]
    return spawns


# ─────────────────────────────────────────────────────────────────────────────
# Planned image paths
# ─────────────────────────────────────────────────────────────────────────────

def slug(s):
    """Lower-kebab a label the way the collectables image folders do."""
    s = (s or "").replace("'", "").replace("’", "")
    s = re.sub(r"[^A-Za-z0-9]+", "-", s).strip("-").lower()
    return re.sub(r"-{2,}", "-", s)


def plan_path(region, marker, label, kind):
    """kind: 'map' (image_top) or 'item' (image_bottom)."""
    return "%s/%s-%s-%s-%s.avif" % (
        IMG_BASE, slug(region), slug(marker), slug(label), kind
    )


def marker_map_path(region, marker):
    """One Pip-Boy map shot per MARKER (multi-spawn markers)."""
    return "%s/%s-%s-map.avif" % (IMG_BASE, slug(region), slug(marker))


def _have(path):
    """True if the converted AVIF for this site path is staged locally."""
    return bool(path) and os.path.exists(
        os.path.join(AVIF_DIR, os.path.basename(path))
    )


def set_slot(obj, field, path, hits):
    """Point `field` at `path` if the AVIF exists, else park it in _planned."""
    planned = field + "_planned"
    if _have(path):
        obj[field] = path
        obj.pop(planned, None)
        hits["live"] += 1
    else:
        obj[field] = ""
        obj[planned] = path
        hits["planned"] += 1


# ─────────────────────────────────────────────────────────────────────────────

def apply(path):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as fh:
        d = json.load(fh)

    hits = {"marker": [], "spawn": [], "planned": 0, "live": 0, "missing": []}

    for reg in d.get("regions", []):
        region = reg.get("region", "")
        for loc in reg.get("locations", []):
            mk = loc.get("marker", "")
            spawns = loc.get("spawns") or []

            # Walk order + renumbered labels BEFORE anything reads a label.
            spawns = reorder_and_relabel(loc)

            # Marker-level "Getting there" (multi-spawn markers only).
            if mk in MARKER_DIRECTIONS and len(spawns) > 1:
                loc["directions"] = MARKER_DIRECTIONS[mk]
                hits["marker"].append(mk)

            for sp in spawns:
                ref = (sp.get("ref") or "").upper()
                label = sp.get("label") or "spawn"

                if ref in SPAWN_DIRECTIONS:
                    sp["directions"] = SPAWN_DIRECTIONS[ref]
                    hits["spawn"].append("%s / %s" % (mk, label))
                else:
                    hits["missing"].append("%s / %s (%s)" % (mk, label, ref))

                # Photos are shot as ONE Pip-Boy map per marker plus one
                # in-world shot per spawn, so only single-spawn markers get a
                # per-spawn map slot — there the marker and the spawn are the
                # same place. Multi-spawn markers carry the map at marker level.
                if len(spawns) == 1:
                    set_slot(sp, "image_top", plan_path(region, mk, label, "map"), hits)
                else:
                    sp["image_top"] = ""
                    sp.pop("image_top_planned", None)
                set_slot(sp, "image_bottom", plan_path(region, mk, label, "item"), hits)

            # Marker-level map shot (multi-spawn markers only).
            if len(spawns) > 1:
                set_slot(loc, "image_top", marker_map_path(region, mk), hits)
            else:
                loc["image_top"] = ""
                loc.pop("image_top_planned", None)
            loc["image_bottom"] = ""
            loc.pop("image_bottom_planned", None)

            # Single-spawn markers render via loc.directions || spawn.directions.
            # Keep the marker field clear so the spawn text is what shows.
            if len(spawns) == 1 and mk not in MARKER_DIRECTIONS:
                loc["directions"] = loc.get("directions") or ""

    with open(path, "w", encoding="utf-8") as fh:
        json.dump(d, fh, ensure_ascii=False, indent=1)
    return hits


def main():
    targets = [
        os.path.join(REPO, "dist", "farming_spawns", "deathclaw-egg_spawns.json"),
        os.path.join(REPO, "dist", "pts", "farming_spawns", "deathclaw-egg_spawns.json"),
    ]
    rc = 0
    for p in targets:
        hits = apply(p)
        if hits is None:
            print("  [skip] %s (not present)" % os.path.relpath(p, REPO))
            continue
        print("  %s" % os.path.relpath(p, REPO))
        print("    marker-level : %d" % len(hits["marker"]))
        print("    spawn-level  : %d" % len(hits["spawn"]))
        print("    live images  : %d" % hits["live"])
        print("    still planned: %d" % hits["planned"])
        if hits["missing"]:
            rc = 1
            print("    !! NO DIRECTIONS for %d spawn(s):" % len(hits["missing"]))
            for m in hits["missing"]:
                print("       - %s" % m)
    return rc


if __name__ == "__main__":
    sys.exit(main())
