#!/usr/bin/env python3
"""
diff_live_pts.py
================
Compare the LIVE data channel (dist/) against the PTS channel (dist/pts/) and
report what changed — the answer to "Bethesda didn't tell us what's different
on the test server."

For every JSON file that exists in both channels it tries a record-level diff
(added / removed / changed) keyed on an id-like field (FormID, EDID, id, name).
Files that are pure dicts or lack an id field fall back to a structural compare.
Files present in only one channel are reported as new/removed.

Outputs a readable Markdown changelog (default dist/pts/_pts_changelog.md) and,
with --json, a machine-readable dist/pts/_pts_changelog.json.

Usage:
  python diff_live_pts.py
  python diff_live_pts.py --live dist --pts dist/pts --out dist/pts/_pts_changelog.md --json
"""

import argparse
import json
import os
import sys

ID_FIELDS = ["FormID", "formid", "form_id", "EDID", "edid", "id", "key",
             "Name", "name", "title", "slug"]
# files we never diff (they ARE the diff, or are noise)
SKIP_BASENAMES = {"_pts_changelog.json", "_pts_changelog.md"}
SKIP_SUBSTR = ["patchlog", "manifest", "diagnostics", "_history"]


def load_json(path):
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        return {"__error__": str(e)}


def rel_json_files(root):
    out = set()
    for dirpath, _dirs, files in os.walk(root):
        # don't descend into a nested pts/ when scanning live
        for fn in files:
            if not fn.endswith(".json"):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root)
            out.add(rel.replace(os.sep, "/"))
    return out


def find_records(obj):
    """Return a list[dict] of records from a JSON doc, or None if not list-like."""
    if isinstance(obj, list) and obj and all(isinstance(x, dict) for x in obj):
        return obj
    if isinstance(obj, dict):
        # common wrappers
        for k in ("items", "records", "data", "rows", "entries"):
            v = obj.get(k)
            if isinstance(v, list) and v and all(isinstance(x, dict) for x in v):
                return v
    return None


def pick_key(records):
    for f in ID_FIELDS:
        if all(f in r for r in records):
            # must be reasonably unique
            vals = [str(r[f]) for r in records]
            if len(set(vals)) >= max(2, int(len(vals) * 0.9)):
                return f
    return None


def diff_records(live, pts, key):
    lm = {str(r[key]): r for r in live}
    pm = {str(r[key]): r for r in pts}
    added = sorted(set(pm) - set(lm))
    removed = sorted(set(lm) - set(pm))
    changed = []
    for k in sorted(set(lm) & set(pm)):
        if lm[k] != pm[k]:
            fields = sorted({f for f in set(lm[k]) | set(pm[k])
                             if lm[k].get(f) != pm[k].get(f)})
            label = pm[k].get("Name") or pm[k].get("name") or pm[k].get("EDID") or k
            changed.append((k, label, fields))
    return added, removed, changed, lm, pm


def label_for(m, k):
    r = m.get(k, {})
    return r.get("Name") or r.get("name") or r.get("EDID") or r.get("edid") or k


def main():
    ap = argparse.ArgumentParser(description="Diff live dist vs PTS dist.")
    ap.add_argument("--live", default="dist")
    ap.add_argument("--pts", default="dist/pts")
    ap.add_argument("--out", default="dist/pts/_pts_changelog.md")
    ap.add_argument("--json", action="store_true", help="also write a JSON changelog next to --out")
    ap.add_argument("--max-items", type=int, default=40, help="max items listed per section per file")
    args = ap.parse_args()

    if not os.path.isdir(args.pts):
        print(f"[diff] PTS dir not found: {args.pts}", file=sys.stderr)
        sys.exit(1)

    live_files = rel_json_files(args.live)
    # exclude the nested pts tree from the live listing
    live_files = {f for f in live_files if not f.startswith("pts/")}
    pts_files = rel_json_files(args.pts)

    def skip(rel):
        base = os.path.basename(rel)
        return base in SKIP_BASENAMES or any(s in rel.lower() for s in SKIP_SUBSTR)

    common = sorted(f for f in (live_files & pts_files) if not skip(f))
    only_pts = sorted(f for f in (pts_files - live_files) if not skip(f))
    only_live = sorted(f for f in (live_files - pts_files) if not skip(f))

    md = ["# PTS vs Live — data changelog",
          "",
          f"Comparing **live** (`{args.live}`) against **PTS** (`{args.pts}`).",
          "",
          "_Generated by diff_live_pts.py. PTS data is ahead of live and may be "
          "incomplete or wrong — treat as a preview._",
          ""]
    jsonlog = {"new_files": only_pts, "removed_files": only_live, "files": {}}

    total_changed_files = 0
    for rel in common:
        live_obj = load_json(os.path.join(args.live, rel))
        pts_obj = load_json(os.path.join(args.pts, rel))
        if live_obj == pts_obj:
            continue
        total_changed_files += 1
        lr = find_records(live_obj)
        pr = find_records(pts_obj)
        key = pick_key(pr) if pr else None
        if lr is not None and pr is not None and key and pick_key(lr) == key:
            added, removed, changed, lm, pm = diff_records(lr, pr, key)
            md.append(f"## `{rel}`  ·  +{len(added)} / -{len(removed)} / ~{len(changed)}")
            jsonlog["files"][rel] = {
                "key": key,
                "added": added, "removed": removed,
                "changed": [{"key": k, "label": lbl, "fields": fl} for k, lbl, fl in changed],
            }
            if added:
                md.append(f"\n**Added ({len(added)})**")
                for k in added[:args.max_items]:
                    md.append(f"- {label_for(pm, k)}  `{k}`")
                if len(added) > args.max_items:
                    md.append(f"- …and {len(added) - args.max_items} more")
            if removed:
                md.append(f"\n**Removed ({len(removed)})**")
                for k in removed[:args.max_items]:
                    md.append(f"- {label_for(lm, k)}  `{k}`")
                if len(removed) > args.max_items:
                    md.append(f"- …and {len(removed) - args.max_items} more")
            if changed:
                md.append(f"\n**Changed ({len(changed)})**")
                for k, lbl, fields in changed[:args.max_items]:
                    md.append(f"- {lbl}  `{k}` — fields: {', '.join(fields)}")
                if len(changed) > args.max_items:
                    md.append(f"- …and {len(changed) - args.max_items} more")
            md.append("")
        else:
            md.append(f"## `{rel}`  ·  changed (structural)")
            md.append("_Couldn't key this file to records; contents differ._\n")
            jsonlog["files"][rel] = {"structural_change": True}

    if only_pts:
        md.append("## New files (PTS only)")
        for f in only_pts:
            md.append(f"- `{f}`")
        md.append("")
    if only_live:
        md.append("## Files missing from PTS")
        for f in only_live:
            md.append(f"- `{f}`")
        md.append("")

    header_summary = (f"**{total_changed_files}** file(s) changed, "
                      f"**{len(only_pts)}** new, **{len(only_live)}** missing.")
    md.insert(5, header_summary + "\n")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    print(f"[diff] wrote {args.out}")
    print(f"[diff] {header_summary}")

    if args.json:
        jp = os.path.splitext(args.out)[0] + ".json"
        with open(jp, "w", encoding="utf-8") as f:
            json.dump(jsonlog, f, ensure_ascii=False, indent=2)
        print(f"[diff] wrote {jp}")


if __name__ == "__main__":
    main()
